- Exercici 1

Descarrega el data set Airlines Delay: Airline on-time statistics and delay causes i carrega’l a un Pandas Dataframe. Explora les dades que conté, explica breument quines variables hi ha i queda’t únicament amb les columnes que consideris rellevants. Justifica la teva elecció.



Important

Redueix la dimensió del dataset de manera aleatòria per tal d'obtenir un dataset de només 200.000 registres. Tots els exercicis s'han de fer amb aquest dataset reduït.

--------------------------------------------------------------------------------------------------

In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
airlines_df=pd.read_csv ("DelayedFlights.csv")
airlines_df=airlines_df.sample(n=200000, frac=None, replace=False, weights=None, random_state=None)

In [2]:
airlines_df

,Unnamed: 0,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
660726,2132069,2008,4,10,4,1945.0,1905,2040.0,2005,F9,...,10.0,12.0,0,N,0,0.0,0.0,24.0,0.0,11.0
100434,323468,2008,1,2,3,750.0,710,948.0,915,EV,...,12.0,8.0,0,N,0,33.0,0.0,0.0,0.0,0.0
206241,662394,2008,2,20,3,2241.0,2020,2348.0,2130,WN,...,4.0,8.0,0,N,0,0.0,0.0,0.0,0.0,138.0
100338,323236,2008,1,7,1,1946.0,1940,2000.0,2009,EV,...,3.0,12.0,0,N,0,NaN,NaN,NaN,NaN,NaN
1326587,4463727,2008,8,9,6,2220.0,2212,604.0,619,UA,...,4.0,10.0,0,N,0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599042,1875611,2008,4,28,1,1746.0,1715,1826.0,1745,WN,...,4.0,9.0,0,N,0,20.0,0.0,10.0,0.0,11.0
1846840,6765684,2008,12,27,6,1533.0,1419,1733.0,1635,EV,...,8.0,8.0,0,N,0,20.0,0.0,0.0,0.0,38.0
1323709,4454450,2008,8,5,2,1829.0,1719,2134.0,2112,UA,...,5.0,19.0,0,N,0,16.0,0.0,0.0,0.0,6.0
537392,1684622,2008,3,13,4,1221.0,1205,1751.0,1729,AA,...,11.0,12.0,0,N,0,16.0,0.0,6.0,0.0,0.0
1594928,5757681,2008,10,5,7,1553.0,1520,1633.0,1605,MQ,...,4.0,10.0,0,N,0,28.0,0.0,0.0,0.0,0.0

Hi ha variables des de número de vol, any (sempre és el mateix evidentment) data, hores de sortida i arribada reals i previstes, temps a pista, temps de vol, origen, destí, distància...
He decidit quedar-me amb els delays, amb les distàncies, amb les destinacions i les dates per tal de poder establir alguna relació entre aquestes variables.

In [3]:
airlines_df_filtrat= airlines_df[["Month","DayofMonth","DepTime", "CRSDepTime","ArrTime","CRSArrTime", "AirTime", "ArrDelay", "DepDelay","Origin", "Dest", "Distance"]]
print (airlines_df_filtrat)

         Month  DayofMonth  DepTime  CRSDepTime  ArrTime  CRSArrTime  AirTime  \
660726       4          10   1945.0        1905   2040.0        2005     93.0
100434       1           2    750.0         710    948.0         915     98.0
206241       2          20   2241.0        2020   2348.0        2130     55.0
100338       1           7   1946.0        1940   2000.0        2009     59.0
1326587      8           9   2220.0        2212    604.0         619    270.0
...        ...         ...      ...         ...      ...         ...      ...
599042       4          28   1746.0        1715   1826.0        1745     87.0
1846840     12          27   1533.0        1419   1733.0        1635    104.0
1323709      8           5   1829.0        1719   2134.0        2112    341.0
537392       3          13   1221.0        1205   1751.0        1729    187.0
1594928     10           5   1553.0        1520   1633.0        1605     26.0

         ArrDelay  DepDelay Origin Dest  Distance
660726       35.0      40.0    DFW  DEN       641
100434       33.0      40.0    ORF  ATL       516
206241      138.0     141.0    DAL  AMA       324
100338       -9.0       6.0    ATL  GPT       352
1326587     -15.0       8.0    LAX  BWI      2329
...           ...       ...    ...  ...       ...
599042       41.0      31.0    RDU  BNA       443
1846840      58.0      74.0    GRR  ATL       640
1323709      22.0      70.0    JFK  SFO      2586
537392       22.0      16.0    TUS  ORD      1437
1594928      28.0      33.0    ORD  MSN       109

[200000 rows x 12 columns]

- Exercici 2

Fes un informe complet del dataset:

    Resumeix estadísticament el dataset i les columnes d’interès. Fes una anàlisi estadístic del que consideris rellevant.
    Troba quantes dades faltants hi ha per columna.
    Crea columnes noves (velocitat mitjana del vol, si ha arribat tard o no...).
    Fes una taula de les aerolínies amb més endarreriments acumulats.
    Quins són els vols més llargs? I els més endarrerits? Busca les rutes més llargues i les que acumulen més retards.
    Aporta allò que consideris rellevant.

In [4]:
airlines_df_filtrat.describe()

,Month,DayofMonth,DepTime,CRSDepTime,ArrTime,CRSArrTime,AirTime,ArrDelay,DepDelay,Distance
count,200000.000000,200000.000000,200000.000000,200000.000000,199272.000000,200000.000000,199152.000000,199152.000000,200000.000000,200000.000000
mean,6.123465,15.733460,1519.300755,1468.547170,1610.244761,1635.366415,108.578970,42.085558,43.051785,768.008180
std,3.480081,8.779223,449.596963,424.001507,548.760661,464.528271,68.817845,56.373344,52.905460,574.883292
min,1.000000,1.000000,1.000000,5.000000,1.000000,0.000000,2.000000,-69.000000,6.000000,31.000000
25%,3.000000,8.000000,1204.000000,1135.000000,1317.000000,1325.000000,58.000000,9.000000,12.000000,340.000000
50%,6.000000,16.000000,1546.000000,1510.000000,1715.000000,1706.000000,91.000000,24.000000,24.000000,611.000000
75%,9.000000,23.000000,1900.000000,1815.000000,2030.000000,2015.000000,138.000000,56.000000,53.000000,1005.000000
max,12.000000,31.000000,2400.000000,2359.000000,2400.000000,2400.000000,641.000000,1370.000000,1521.000000,4962.000000

In [5]:
np.corrcoef(airlines_df[["ArrDelay","Distance"]])

MemoryError: Unable to allocate 298. GiB for an array with shape (200000, 200000) and data type float64

In [ ]:
print (airlines_df["ArrDelay"].describe())
print (airlines_df["Distance"].describe())

Exporta el dataset net i amb les noves columnes a Excel.